var express = require('express');
var app = express();

app.get('/groups', function (req, res) {

    var data = {
        "items": [{
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 598,
            "name": "JPEO",
            "description": "A collaboration group for JPEO staff",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1444955551784,
            "lastModifiedAt": 1500096344029,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 598,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 599,
            "name": "Combined US and ROK BSP",
            "description": "This is the Combined US and ROK BSP group. An open collaboration space for Biosurveillance among ROK and US users in Korea.",
            "pdcBookmarkUrl": null,
            "fouo": false,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1445022397994,
            "lastModifiedAt": 1455123908587,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 599,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 600,
            "name": "ROK Republic of Korea",
            "description": "A biosurveillance collaboration space for ROK users",
            "pdcBookmarkUrl": "https://jpeobsp.pdc.org/jpeo/?bookmark=7408",
            "fouo": false,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1445022497174,
            "lastModifiedAt": 1484698825055,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 600,
            "canReceiveRfis": false
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 601,
            "name": "USFK",
            "description": "A biosurveillance collaboration space for US Forces Korea",
            "pdcBookmarkUrl": null,
            "fouo": false,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1445022567431,
            "lastModifiedAt": 1445022567431,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 601,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 665,
            "name": "SIL BSP System Integration Lab Korea",
            "description": "A collaboration space for the BSP System Integration laboratory (SIL) in Korea",
            "pdcBookmarkUrl": null,
            "fouo": false,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1445022648327,
            "lastModifiedAt": 1445022648327,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 665,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 2835,
            "name": "Zika Virus",
            "description": "Biosurveillance Portal group supporting the control of the Zika virus disease through information sharing and collaboration",
            "pdcBookmarkUrl": null,
            "fouo": false,
            "imageDocumentId": 3076,
            "accessType": "PUBLIC",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": true,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1454655913991,
            "lastModifiedAt": 1500096344044,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 2835,
            "canReceiveRfis": true
        }, {
            "creator": 1498,
            "lastModifiedBy": 728,
            "owner": 1498,
            "id": 5145,
            "name": "G-BSP Systems Engineering",
            "description": "For BSP PMO Internal Use Only - Engineering documents supporting BSP development, integration, and test",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": 57990,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1458770494068,
            "lastModifiedAt": 1500048963657,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 5145,
            "canReceiveRfis": true
        }, {
            "creator": 1498,
            "lastModifiedBy": 10,
            "owner": 1498,
            "id": 8071,
            "name": "G-BSP User Help Desk",
            "description": "A resource site for current BSP users",
            "pdcBookmarkUrl": null,
            "fouo": false,
            "imageDocumentId": 57984,
            "accessType": "PUBLIC",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": true,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1465949342589,
            "lastModifiedAt": 1500096344058,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 8069,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 14735,
            "name": "Cybersecurity IPT",
            "description": "The Cyber IPT focuses on communication and coordination among GBSP Cybersecurity stakeholders, in order to promote cybersecurity awareness, identify cybersecurity issues, and recommend potential solutions to cybersecurity problems, thereby helping to enhance overall GBSP cybersecurity protection.",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": 57987,
            "accessType": "PRIVATE",
            "discoverable": false,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1467997633131,
            "lastModifiedAt": 1484698312412,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 14716,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 23919,
            "name": "PDC BSP Team",
            "description": "PDC (MAP Application Administrator) Troubleshooting",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PRIVATE",
            "discoverable": false,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1471294869917,
            "lastModifiedAt": 1477587181599,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 23927,
            "canReceiveRfis": true
        }, {
            "creator": 1498,
            "lastModifiedBy": 36827,
            "owner": 1498,
            "id": 45843,
            "name": "SOCPAC",
            "description": "Collaboration and coordination Group for SOCPAC Medical, Force Health Protection and CBRN staff",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1480559104637,
            "lastModifiedAt": 1489467910646,
            "organization": {
                "website": "https://socpac.sof.socom.mil/SitePages/Home.aspx",
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "Camp H.M. Smith",
                    "county": null,
                    "state": "HI",
                    "country": "USA",
                    "zipcode": "96861"
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": "808-477-7930",
                "secondaryPhone": "808-477-7920",
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 45474,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 59185,
            "name": "AFHSB Products",
            "description": "NOT PROVIDED",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PUBLIC",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": true,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1485213228281,
            "lastModifiedAt": 1500096344073,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 59180,
            "canReceiveRfis": false
        }, {
            "creator": 10,
            "lastModifiedBy": 56868,
            "owner": 10,
            "id": 64050,
            "name": "FilmArray Community of Interest",
            "description": "FilmArray Community of Interest",
            "pdcBookmarkUrl": "https://www.biosurveillanceportal.org/",
            "fouo": true,
            "imageDocumentId": 96680,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1486525614021,
            "lastModifiedAt": 1495224067618,
            "organization": {
                "website": "https://www.biosurveillanceportal.org/",
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": "osd.detrick.ousd-atl.list.filmarray-coi-user-group-inbox1@mail.mil",
                "secondaryEmail": "matthew.j.becker37.ctr@mail.mil",
                "primaryPhone": "3016198468",
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 64049,
            "canReceiveRfis": false
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 79999,
            "name": "BICS",
            "description": "A collaboration group for the Biological Identification Capabilities Sets (BICS)",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1491269961611,
            "lastModifiedAt": 1491269961611,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 80215,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 90279,
            "name": "SOCNORTH",
            "description": "A group for SOCNORTH and their partners for all hazards communications and collaboration.",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1493339239856,
            "lastModifiedAt": 1493339239856,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 90267,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 92316,
            "name": "353rd (AFSOC)",
            "description": "NOT PROVIDED",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1493847305112,
            "lastModifiedAt": 1494034734279,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 92323,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 92317,
            "name": "1/1SFG(A)",
            "description": "NOT PROVIDED",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1493847435662,
            "lastModifiedAt": 1494034754897,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 92335,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 92318,
            "name": "1st SFG(A) HQ",
            "description": "NOT PROVIDED",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1493847558105,
            "lastModifiedAt": 1494034744470,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 92348,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 92319,
            "name": "Unit 1 (NSW)",
            "description": "NOT PROVIDED",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1493847625736,
            "lastModifiedAt": 1494034873623,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 92361,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 92320,
            "name": "Raider 1 (MARSOC)",
            "description": "NOT PROVIDED",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1493847702546,
            "lastModifiedAt": 1494034709045,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 92373,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 92321,
            "name": "G-BSP Testing",
            "description": "A collaboration space for GBSP Testing Resources and Testers within the GBSP Support Team",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PRIVATE",
            "discoverable": false,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1494013988496,
            "lastModifiedAt": 1500046992873,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 93144,
            "canReceiveRfis": false
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 93303,
            "name": "SOCCENT",
            "description": "NOT PROVIDED",
            "pdcBookmarkUrl": null,
            "fouo": true,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1494034544450,
            "lastModifiedAt": 1494034650688,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 93298,
            "canReceiveRfis": false
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 101535,
            "name": "NORTHCOM CBRN Summit",
            "description": "A demonstration group",
            "pdcBookmarkUrl": null,
            "fouo": false,
            "imageDocumentId": null,
            "accessType": "PUBLIC",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": true,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1496264682324,
            "lastModifiedAt": 1496264682324,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 101491,
            "canReceiveRfis": true
        }, {
            "creator": 10,
            "lastModifiedBy": 10,
            "owner": 10,
            "id": 103110,
            "name": "JPEO Non-FOUO Group",
            "description": "Non-FOUO group to support JPEO operations and testing in PROD",
            "pdcBookmarkUrl": null,
            "fouo": false,
            "imageDocumentId": null,
            "accessType": "PROTECTED",
            "discoverable": true,
            "publicReadable": false,
            "openMembership": false,
            "startDate": null,
            "itemType": "GROUP",
            "createdAt": 1496687794350,
            "lastModifiedAt": 1496687794350,
            "organization": {
                "website": null,
                "address": {
                    "address1": "",
                    "address2": "",
                    "city": "",
                    "county": null,
                    "state": "",
                    "country": "",
                    "zipcode": ""
                },
                "primaryEmail": null,
                "secondaryEmail": null,
                "primaryPhone": null,
                "secondaryPhone": null,
                "facebookHandle": null,
                "twitterHandle": null,
                "googlePlusHandle": null
            },
            "docLibFolder": 103118,
            "canReceiveRfis": true
        }]
    };
    res.setHeader('Content-Type', 'application/json');
    res.setHeader('Access-Control-Allow-Credentials', 'true');
    res.setHeader('Access-Control-Allow-Methods', 'POST, GET, PUT, DELETE, OPTIONS');
    res.setHeader('Access-Control-Allow-Origin', 'http://localhost');
    console.log(data);
    res.send(data);
});

// app.put('/setUserAccount', function (req, res) {
//
// 	var data = req.params.data;
//
//     res.setHeader('Content-Type', 'application/json');
//     res.setHeader('Access-Control-Allow-Credentials', 'true');
//     res.setHeader('Access-Control-Allow-Methods', 'POST, GET, PUT, DELETE, OPTIONS');
//     res.setHeader('Access-Control-Allow-Origin', 'http://localhost');
//     res.send('Saved');
// });

app.listen(8000, function () {
	console.log('Server running on 8000!');
});
